name: BGUHC
version: 1.0.0
api: [
        3.0.0-ALPHA5,
        3.0.0-ALPHA4,
        3.0.0-ALPHA3,
        3.0.0-ALPHA2,
        3.0.0-ALPHA1,
        3.0.0,
        2.1.0,
        2.0.0
    ]
author: SpopovabgS
main: bguhc\Main
commands:
    bguhc:
        description: "Main UHC command."
